version: "3.9"

services:
  api:
    image: api-exam-system
    container_name: exam-system-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;
        Database=ExamSystemDB;
        User Id=sa;
        Password=Password12345;
        TrustServerCertificate=True;
      ConnectionStrings__RedisConnection: redis:6379
    depends_on:
      - sqlserver
      - redis

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: exam-system-sql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password12345"
    volumes:
      - sqlserver_data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: exam-system-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  sqlserver_data:
  redis_data:
